### ISSUE TITLE
How to keep non-coincident MAGIC-stereo events?

### ISSUE THREAD

**Issue by YoshikiOhtani** [cta-observatory/magic-cta-pipe#108]
The current pipeline does not keep MAGIC-stereo events which are not coincident with any LST-1 events, since they are thought to be mostly hadronic origin. However, in order to properly compare the trigger rates, the fractions of telescope combination types between real data and MCs, etc, it would be good to keep them.

One issue that I came up with is how to label observation and event IDs for those events. In case of real data, the pipeline currently assigns LST observation and event IDs to coincident MAGIC events, and use the IDs to group telescope-wise events. However, it is not possible to assign any LST event IDs to non-coincident MAGIC-stereo events, and assigning NaN values to those event IDs will crash the pipeline, so we need a solution for this problem.

I think using MAGIC observation and event IDs instead would be a good solution, because we keep only LST-1 events coincident with MAGIC events so it's possible to assign the MAGIC IDs to the LST-1 events. But in this way, it would be needed to also change the scripts of later analysis stages. Currently in real data, the `obs_id` and `event_id` variables indicate LST observation and event IDs, and there are also `obs_id_magic` and `event_id_magic` variables to store the MAGIC IDs. I think it is better to keep those names and roles in the future, because now real data events are put together per LST observation or subrun IDs (e.g., `dl1_LST-1_MAGIC.Run${LST_RunID}.${LST_SubRunID}.h5`), so the IDs of their file names should be consistent with the `obs_id` and `event_id` variables. However, in the later stages when we group telescope-wise events, it currently uses `obs_id` and `event_id`, which will not work for non-coincident MAGIC events because they are NaN. Thus, we need to change the scripts to use `obs_id_magic` and `event_id_magic` instead to properly group the events of any telescope combination types for real data.

It would be great if you could give me any thoughts on this solution, or any other ideas or suggestions are also very welcome. If we agree on this solution, I can start to push some commits to implement this solution.

**Comment by jsitarek** [comment]
@YoshikiOhtani the pipeline works also for MAGIC-only data, where of course the same problem should happen by definition for all the events. Does it use obs_id_magic and event_id_magic as keys for grouping the images? Then it is of course simpler because there are no LST1 events at all

Now about the problem at hand when we have all the telescope combinations, how about such a solution, we already have {obs,event}_id_magic, and he keep it as it is (I guess it is using the MARS run number and L3 stereo event number, right?) 
for proper book keeping we can introduce also {obs,event}_id_lst, which might be NaN if it is a non-LST1 event.
And what we use for grouping the events is {obs,event}_id that would be defined as:
{obs,event}_id = {obs,event}_id_lst (if LST1 is present, as it was)
{obs,event}_id = - {obs,event}_id_magic (if it is M1+M2 event)

this way the identifiers are still unique, even if by chance the LST1 event number is equal to MAGIC L3 number. We can still easily see if the number comes from MAGIC or from LST1 by its sign, and the rest of the chain should work without any change needed.
The only tiny problem is that events would not be sequential if ordered by event_id, but this is not really a problem, because you can always order the events by timestamps if it is required. What do you think?

**Comment by YoshikiOhtani** [comment]
Hi @jsitarek, thanks for your fast response. Indeed I forgot about the MAGIC-only analysis, where there are not `obs_id_magic` and `event_id_magic` variables (only `obs_id` and `event_id` exist) so my solution does not work.

Yes, the `obs_id_magic` and `event_id_magic` come from what you said. And it's a good idea that we create the `obs_id_lst` and `event_id_lst` variables, and assign LST or MAGIC IDs to `obs_id` and `event_id` based on the telescope combination types. I think just using MAGIC observation + event IDs are already unique even if the event IDs are same, because LST and MAGIC observation IDs in principle never match, so it is not absolutely necessary to use sign for the MAGIC IDs. Actually I was also thinking to use sign, but for my personal opinion it looks strange... and people may be also confused, so I would like to avoid using it.

So what I agree is as follows, just removing the sign from the second condition:
{obs,event}_id = {obs,event}_id_lst (if LST1 is present, as it was)
{obs,event}_id = {obs,event}_id_magic (if it is M1+M2 event)

What do you think?
