### ISSUE TITLE
Saved telescope positions in MC are "wrong"

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/magic-cta-pipe#135]
The saved telescope positions are relative to the unweighted average of the 3 telescopes. This will result in positions which are not consistent with the reconstructed or true core positions stored event-wise. This is very confusing!

https://github.com/cta-observatory/magic-cta-pipe/blob/dbcb3442683b26d7a03fb3be72e375eb199d5e72/magicctapipe/scripts/lst1_magic/lst1_magic_mc_dl0_to_dl1.py#L411-L418

**Comment by moralejo** [comment]
In the stereo reconstruction the saved telescope positions are used, both for reco and for later calculating impact, so there should be no problem. What cannot be done is comparing reconstructed core positions with true ones.
On the other hand, true_impact can be compared to the reco one - both should be "correct", just calculated in different coordinate frames.

**Comment by jsitarek** [comment]
Hi,

This seems to have been introduced back in Jan 2022
https://github.com/cta-observatory/magic-cta-pipe/commit/1b5de6c7c26d7057cf5adf7392fda2e3da10dec5#diff-c03540ef6e8c11788e815e8f9f45e8ca165091703d5e1180fe549160c928ef63
Maybe it was related with the first simulations of Yoshiki (maybe they were using the positions shifted w.r.t. COG)
@YoshikiOhtani can you comment?
I agree with Abelardo that it is confusing, even if it does not affect the rest of the chain.

**Comment by YoshikiOhtani** [comment]
Hi @moralejo and @jsitarek, apologies for a late response. Yes, I introduced these lines to transform the center of the coordinate to the "unweighted" average of the telescope positions. When I was developing this script, I was still using the old MCs (prod5 with 4LSTs+MAGIC) in which all the telescope Z positions were set to the height ~40 m higher than the observation level (= 2158 m). Since the core position is calculated at the height Z = 0, the true and reconstructed core positions looked a bit shifted and thus confusing at that time. In order to make the positions understandable, at least the reconstructed ones, I decided to transform the coordinate before reconstructing the stereo parameters.

However I agree with you that it is not needed now, since the all sky MCs are produced with a higher observation level so the core positions look already understandable. I can push a commit to get rid of this transformation, but I guess it would be better to change the version of the pipeline once I do so.

**Comment by aleberti** [comment]
@jsitarek @moralejo is this still relevant? should we get rid of the corresponding lines? now with the changes from Elisa/Raniere it has also the 4 telescopes.

https://github.com/cta-observatory/magic-cta-pipe/blob/master/magicctapipe/scripts/lst1_magic/lst1_magic_mc_dl0_to_dl1.py#L399-L413

**Comment by jsitarek** [comment]
Since either way we had a bunch of breaking changes and still did not start with any massive processing it seems like a good idea to clean it up now.

**Comment by aleberti** [comment]
Ok, I will open a PR later. I first want to understand why some tests fail...
