### ISSUE TITLE
Problem installing MCP on windows: protozfits 

### ISSUE THREAD

**Issue by FedericoDevoto757** [cta-observatory/magic-cta-pipe#215]
Good evening I am a new master thesis student in Torino, I am trying to install MCP on my windows pc but i get the following error:  nothing provides protozfits >=2.2,<3.dev0 needed by ctapipe_io_lst-0.220
![Screenshot 2024-03-21 152538](https://github.com/cta-observatory/magic-cta-pipe/assets/151157377/22610e54-9de6-469a-957c-e17c82bdff7f)
Thanks for the help.

Federico Devoto

**Comment by aleberti** [comment]
indeed, protozfits is not available on windows, so since you are trying to build it on windows, it cannot work. What I can recommend, is to install the Windows Subsystem for Linux (WSL, already mentioned by Elisa), which provides you with a linux environment (e.g. from the latest distributions Ubuntu 20.04 or 22.04), where you can install conda and later MCP. That will work (I already did it on my personal laptop which also has windows).

if you are asking yourself why protozfits is not available on windows, unfortunately I cannot answer, this is a question for the developers of that package.

**Comment by Elisa-Visentin** [comment]
You could also try with a Virtual Machine (VMWare or VirtualBox) to have a completely 'fail-safe' linux machine (if you damage it, you destroy it and create a new one)

**Comment by FedericoDevoto757** [comment]
Thank you very much, I will try to use Windows Subsystem for Linux since I have it already installed.
