### ISSUE TITLE
Error with jupyter notebook on WSL

### ISSUE THREAD

**Issue by FedericoDevoto757** [cta-observatory/magic-cta-pipe#216]
Good evening, I'm having troubles starting jupyter notebook in WSL.
![errore2](https://github.com/cta-observatory/magic-cta-pipe/assets/151157377/9884f740-9800-4e0f-b6ab-63129d3ff95b)

It looks like the magic.lst1 ambient has no issues, even the jupyter package seems fine but I still can't open a notebook.
Thanks in advance,

Federico

**Comment by aleberti** [comment]
Hi, I think the problem is that you are running under the `root` user, which is quite unusual. Usually WSL asks you to setup a user at the end of the installation, as it were a classical installation on a laptop. That aside, the log is actually suggesting a possible solution, i.e. adding the `--allow-root` option when calling jupyter. Probably that could work.

However, note that running things as `root` may lead to unexpected problems, not related to MCP itself, like in this case. For example, also `pip` usually does not like being called under `root`.

**Comment by FedericoDevoto757** [comment]
Thank you very much, problem solved.
