### ISSUE TITLE
software_with_any2 excludes MAGIC-only events?

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/magic-cta-pipe#74]
Hi @YoshikiOhtani 

I'm curious about this cut:
https://github.com/cta-observatory/magic-cta-pipe/blob/d6360841d7b5b3d01600bdfcbdb0ffeecb9cc8b0/magicctapipe/scripts/lst1_magic/lst1_magic_create_irf.py#L122-L123

https://github.com/cta-observatory/magic-cta-pipe/blob/d6360841d7b5b3d01600bdfcbdb0ffeecb9cc8b0/magicctapipe/scripts/lst1_magic/lst1_magic_dl2_to_dl3.py#L128-L129

The combo_type cut excludes the events in which you have both MAGIC telescopes, but no LST1. 
Looking at MCs, this is pretty rare, but I'm wondering why such a cut was applied? Is is performance-driven to exclude very bad events, or a technical issue that those events will not have some LST1 information needed?

**Comment by YoshikiOhtani** [comment]
Hi @jsitarek, it is originally introduced because I decided not to keep the MAGIC-stereo events which are NOT coincident with LST-1 after the event coincidence search. This is because from the MC study LST-1 should see most of MAGIC-stereo gamma-ray events, so the most of the non-coincident MAGIC-stereo events should be hadron. Thus, when creating the IRFs I excluded the MAGIC-stereo events from DL2 MC data. 

However, the ratio of the MAGIC-stereo gamma-ray events over the whole stereo events depends on event cuts, e.g., leakage cut would increate the ratio. So it may be good to reconsider about this, what is the best way to treat them.

**Comment by YoshikiOhtani** [comment]
As I reported yesterday, now the pipeline keeps also the MAGIC-stereo events taken during the LST observation time period but not coincident with any LST-1 events. The fraction of those events are relatively high, so it may be worth using the events for the analysis now. However, the problem is that with the current training scheme we do not have enough training samples for the MAGIC-stereo combination type. One alternative solution is to use the `combo_type` parameter in the training instead of separating RFs by the combination types, and in that case we can apply well trained RFs to those MAGIC-stereo events. This is related to the issue #27, so at some point it would be worth testing this scheme, and check how the performance changes.

**Comment by jsitarek** [comment]
closing this as outdated because there is not anymore "software_with_any2"
