### ISSUE TITLE
Bug in the stereo reconstruction of any 2 events

### ISSUE THREAD

**Issue by YoshikiOhtani** [cta-observatory/magic-cta-pipe#92]
I think I found a critical bug in the stereo reconstruction of any 2 events. The problematic lines are here:

https://github.com/cta-observatory/magic-cta-pipe/blob/34dd298f32b662b729945f0fb96e7b88ad2d17af/magicctapipe/scripts/lst1_magic/lst1_magic_stereo_reco.py#L230-L251

Here we reset necessary information to `ArrayEventContainer` event-by-event, but with this code it must happen that the Hillas parameters of the previous event remains in the container and are used for the reconstruction. For example, if the previous event has three images and the next one has LST-1 and MAGIC-I images, the previous MAGIC-II image information remain and is used for the next event reconstruction by mistake. This problem only affects any 2 tel events, since for the events with three images the container is totally updated, and the same thing happen for the MAGIC-only analysis. I did not realize this issue until now, because I usually use only 3-tel events.

A solution is to add just one line `event.reset()` at the begging of the event loop. The reason I did not reset it in the past is that this script only reconstructed the parameters with three images, so the container were every time reset automatically.

@jsitarek I think you used any 2 tel events for your sensitivity study, so this problem should affect the result. I'm sorry for the inconvenience...

I will fix this issue with the pull request #91

**Comment by jsitarek** [comment]
Hi @YoshikiOhtani 
Thanks for finding this, I think it is quite possible that it is the reason for the worse angular resolution at lower energies, where it will be more common to have only 2 images. 
I am wondering if it is better to include `event.reset()` in the loop or to simply move the 
https://github.com/cta-observatory/magic-cta-pipe/blob/34dd298f32b662b729945f0fb96e7b88ad2d17af/magicctapipe/scripts/lst1_magic/lst1_magic_stereo_reco.py#L204
inside the loop. The latter solution looks a bit cleaner, but it might cause some memory issues and performance drops. 

Nevertheless, since the problem is rather serious I would not put it into a general refactoring PR, but a small PR fixing only this should be done (since it is either way only one line, it will not produce much problem with the refactoring PR later on)

**Comment by YoshikiOhtani** [comment]
Hi @jsitarek, thanks for your comments, I agree with the latter solution - it looks clearer than the former one. I think recreating the container object does not affect the performance so much, and anyway the stereo reconstruction is the most significant part to use computing resources. 

OK, I will create another pull request to fix this issue now.
